# -*- coding: utf-8 -*-
"""ImageDescriptionModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfF8MjV4mr1nMzRQBLnfH1waF48kfmt_

# **Run if you have a GPU**
"""

import tensorflow as tf
gpus = tf.config.list_physical_devices('GPU')

if gpus:
    print(f"✅ Success! GPU is available: {gpus}")
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)
else:
    print("❌ GPU not detected. Go to Runtime > Change runtime type and select T4 GPU.")

"""# **Importing the libraries**

"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

"""# **Importing and Reading the Dataset**"""

import kagglehub
path = kagglehub.dataset_download("adityajn105/flickr8k")
print("Path to dataset files:", path)

df=pd.read_csv(path+"/captions.txt")
df

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.image import load_img, img_to_array
img_path = (path+"/Images")

def readimage(path,img_size=224):
    img = load_img(path,color_mode='rgb',target_size=(img_size,img_size))
    img = img_to_array(img)
    img = img/255.
    return img

def display_image(path,img):
    plt.imshow(img)
    plt.axis('off')
    plt.show()
    caption=df[df['image']==path]['caption'].values
    print(caption)

display_image('1000268201_693b08cb0e.jpg',readimage(img_path+'/1000268201_693b08cb0e.jpg'))

"""# **Tokenizing the description**"""

from tensorflow.keras.preprocessing.text import Tokenizer

def preprocess(df):
    df['caption'] = df['caption'].str.lower()
    df['caption'] = df['caption'].str.replace("[^a-z\s]", "", regex=True)
    df['caption'] = df['caption'].str.replace(r"\s+", " ", regex=True)
    df['caption'] = df['caption'].apply(lambda x: " ".join([word for word in x.split() if len(word) > 1]))
    df['caption'] = "startseq " + df['caption'] + " endseq"
    return df

df=preprocess(df)
df

describe=df['caption'].tolist()
describe[:11]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(describe)

images=df['image'].unique().tolist()
images[:11]

"""# **Training And Building The Model**"""

from sklearn.model_selection import train_test_split
x=images
y=[describe[i:i+5] for i in range(0, len(describe), 5)]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train_flat = [img for img in x_train for _ in range(5)]
y_train_flat = [caption for sublist in y_train for caption in sublist]
len(x_train),len(x_test),len(y_train),len(y_test),len(x_train_flat),len(y_train_flat)

from tensorflow.keras import layers, models
BATCH_SIZE = 256
VOCAB_SIZE = 10000
MAX_LENGTH = 32
IMAGE_SIZE = (224, 224)

def load_and_preprocess_image(img_name):
    img_file = tf.strings.join([img_path, "/", img_name])
    img_raw = tf.io.read_file(img_file)
    img_tensor = tf.image.decode_jpeg(img_raw, channels=3)
    img_tensor = tf.image.resize(img_tensor, IMAGE_SIZE)
    img_tensor = img_tensor / 255.0
    return img_tensor

vectorizer = layers.TextVectorization(
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LENGTH
)
vectorizer.adapt(y_train_flat)

def map_dataset(image_name, describe_text):
    img_tensor = load_and_preprocess_image(image_name)
    vectorized_describe = vectorizer(describe_text)
    text_input = vectorized_describe[:-1]
    text_target = vectorized_describe[1:]
    return {
        "image_input_layer": img_tensor,
        "text_input_layer": text_input
    }, text_target

train_dataset_mapped = tf.data.Dataset.from_tensor_slices((x_train_flat, y_train_flat))
train_dataset_mapped = train_dataset_mapped.map(map_dataset, num_parallel_calls=tf.data.AUTOTUNE)
train_dataset_mapped = train_dataset_mapped.shuffle(buffer_size=1024).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

image_input = layers.Input(shape=(224, 224, 3), name="image_input_layer")
x1 = layers.Conv2D(32, (3, 3), activation='relu', padding='same')(image_input)
x1 = layers.MaxPooling2D((2, 2))(x1)
x1 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(x1)
x1 = layers.MaxPooling2D((2, 2))(x1)
x1 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(x1)
x1 = layers.MaxPooling2D((2, 2))(x1)
x1 = layers.Flatten()(x1)
image_features = layers.Dense(256, activation='relu')(x1)

text_input_layer = layers.Input(shape=(MAX_LENGTH - 1,), name="text_input_layer")
x2 = layers.Embedding(input_dim=VOCAB_SIZE, output_dim=256, mask_zero=True)(text_input_layer)
text_features = layers.LSTM(256, return_sequences=True)(x2)

image_features_seq = layers.RepeatVector(MAX_LENGTH - 1)(image_features)
merged_features = layers.add([image_features_seq, text_features])
decoder_dense = layers.TimeDistributed(layers.Dense(256, activation='relu'))(merged_features)
model_outputs = layers.TimeDistributed(layers.Dense(VOCAB_SIZE, activation='softmax'), name="final_word_predictor")(decoder_dense)
model = models.Model(inputs=[image_input, text_input_layer], outputs=model_outputs)

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

model.fit(
    train_dataset_mapped,
    epochs=20,
    verbose=1
)

model.save("image_description_model.keras")

import pickle
with open("vocab.pkl", "wb") as f:
    pickle.dump(vectorizer.get_vocabulary(), f)

